version: '3'

# x-airflow-common:
#   &airflow-common
#   image: airflow
#   environment:
#     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
#     - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
#     - AIRFLOW__CORE__LOAD_EXAMPLES=False
#     - AIRFLOW__CORE__LOGGING_LEVEL=INFO
#   depends_on:
#     - postgres
#   volumes:
#     - airflow_logs:/opt/airflow/logs
#     - airflow_plugins:/opt/airflow/plugins
#     - airflow_scripts:/opt/airflow/scripts
#   networks:
#     - kol-evaluate

services:
  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_USER=airflow
  #     - POSTGRES_PASSWORD=airflow
  #     - POSTGRES_DB=airflow
  #     - POSTGRES_PORT=5432
  #   ports:
  #     - 5432:5432
  #   restart: always
  #   volumes:
  #     - postgres_db_volume:/var/lib/postgresql/data
  #   networks:
  #     - kol-evaluate

  # airflow-init:
  #   << : *airflow-common
  #   container_name: airflow-init
  #   entrypoint: /bin/bash
  #   restart: on-failure
  #   command:
  #     - -c
  #     - airflow db init &&
  #       airflow users create
  #         --role Admin
  #         --username airflow
  #         --password airflow
  #         --email airflow@airflow.com
  #         --firstname airflow
  #         --lastname airflow
  #   networks:
  #     - kol-evaluate

  # airflow-webserver:
  #   << : *airflow-common
  #   container_name: airflow-webserver
  #   ports:
  #     - 8085:8080
  #   restart: always
  #   command: airflow webserver
  #   networks:
  #     - kol-evaluate

  # airflow-scheduler:
  #   << : *airflow-common
  #   container_name: airflow-scheduler
  #   restart: always
  #   command: airflow scheduler
  #   networks:
  #     - kol-evaluate
  test_kp:
    image: hieupt_crawler:1.2
    container_name: test_kp
    restart: always
    ports: 
      - 8090:8090
    networks:
      - kol-evaluate

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./services/hadoop/hadoop.env
    networks:
      - kol-evaluate

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ports:
      - 9864:9864
      - 9866:9866
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./services/hadoop/hadoop.env
    networks:
      - kol-evaluate

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864"
    env_file:
      - ./services/hadoop/hadoop.env
    networks:
      - kol-evaluate

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager1
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 resourcemanager:8088"
    env_file:
      - ./services/hadoop/hadoop.env
    networks:
      - kol-evaluate

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./services/hadoop/hadoop.env
    networks:
      - kol-evaluate

  spark-master:
    image: bitnami/spark:3.3
    container_name: spark-master
    restart: always
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WEBUI_PORT=8080
      - SPARK_SUBMIT_ARGS=--jars /opt/bitnami/iceberg-jars/iceberg-spark-runtime.jar,/opt/bitnami/iceberg-jars/iceberg-hive-runtime.jar \
        --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
        --conf spark.sql.catalog.hadoop=org.apache.iceberg.spark.SparkCatalog \
        --conf spark.sql.catalog.hadoop.type=hive \
        --conf spark.sql.catalog.hadoop.uri=thrift://hive-metastore:9083 \
        --conf spark.sql.catalog.hadoop.warehouse=/user/hive/warehouse
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./hadoop/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
      - ./jars:/opt/bitnami/iceberg-jars
    networks:
      - kol-evaluate

  spark-worker:
    image: bitnami/spark:3.3
    container_name: spark-worker
    restart: always
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_SUBMIT_ARGS=--jars /opt/bitnami/iceberg-jars/iceberg-spark-runtime.jar,/opt/bitnami/iceberg-jars/iceberg-hive-runtime.jar \
        --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
        --conf spark.sql.catalog.hadoop=org.apache.iceberg.spark.SparkCatalog \
        --conf spark.sql.catalog.hadoop.type=hive \
        --conf spark.sql.catalog.hadoop.uri=thrift://hive-metastore:9083 \
        --conf spark.sql.catalog.hadoop.warehouse=/user/hive/warehouse
    depends_on:
      - spark-master
    volumes:
      - ./hadoop/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
      - ./jars:/opt/bitnami/iceberg-jars
    networks:
      - kol-evaluate

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: always
    networks:
      - kol-evaluate

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_NAMES: PLAINTEXT,PLAINTEXT_HOST
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_PORTS: 29092,9092
    volumes:
      - kafka-broker-1-data:/var/lib/kafka/data
    restart: always
    depends_on:
      - zookeeper
    networks:
      - kol-evaluate

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker-2
    ports:
      - "9093:9093"
      - "29093:29093"
    restart: always
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LISTENER_NAMES: PLAINTEXT,PLAINTEXT_HOST
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_PORTS: 29093,9093
    volumes:
      - kafka-broker-2-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - kol-evaluate

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Cluster1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-1:29092,kafka-broker-2:29093
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
    restart: always
    networks:
      - kol-evaluate

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    networks:
      - kol-evaluate
    volumes:
      - hive_metastore_postgresql:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      SERVICE_PRECONDITION: "hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    env_file:
      - ./hadoop/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    restart: always
    networks:
      - kol-evaluate

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8082:8080"
    volumes:
      - ./trino/etc:/etc/trino
    depends_on:
      - hive-metastore
    networks:
      - kol-evaluate

  # superset:
  #   image: apache/superset:latest
  #   container_name: superset
  #   ports:
  #     - "8088:8088"
  #   environment:
  #     - SUPERSET_LOAD_EXAMPLES=yes
  #     - SUPERSET_SECRET_KEY=supersecret
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - trino
  #   volumes:
  #     - superset_home:/app/superset_home
  #     - ./superset/superset-init.sh:/app/run-superset.sh
  #   networks:
  #     - kol-evaluate

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_historyserver:
  zookeeper-data:
  kafka-broker-1-data:
  kafka-broker-2-data:
  # airflow_logs:
  # airflow_plugins:
  # airflow_scripts:
  postgres_db_volume:
  hive_metastore_postgresql:
  metastore_db:
  # superset_home:

networks:
  kol-evaluate:
    driver: bridge
