apiVersion: v1
kind: Service
metadata:
  name: namenode-service
spec:
  type: NodePort
  selector:
    app: hadoop-namenode
  ports:
    - name: web-ui 
      protocol: TCP
      port: 9870
      targetPort: 9870
      nodePort: 30070
    - name: rpc 
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
spec:
  serviceName: "hadoop-namenode"
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870  # Web UI
            - containerPort: 9000  # RPC Port (important for DataNodes)
          env:
            - name: CLUSTER_NAME
              value: "hadoop-cluster"
            - name: HDFS_NAMENODE_RPC_PORT
              value: "9000"
            - name: HDFS_SITE_CONF_dfs_namenode_rpc-address
              value: "0.0.0.0:9000"

          volumeMounts:
            - mountPath: /hadoop/dfs/name
              name: namenode-storage
            - name: hadoop-config
              mountPath: /opt/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
      volumes:
        - name: namenode-storage
          persistentVolumeClaim:
            claimName: namenode-pvc
        - name: hadoop-config
          configMap:
            name: hadoop-config
