apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-nodemanager
spec:
  serviceName: "hadoop-nodemanager"
  replicas: 2
  selector:
    matchLabels:
      app: hadoop-nodemanager
  template:
    metadata:
      labels:
        app: hadoop-nodemanager
    spec:
      containers:
      - name: nodemanager
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
        ports:
        - containerPort: 8042
