apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-resourcemanager
  template:
    metadata:
      labels:
        app: hadoop-resourcemanager
    spec:
      containers:
      - name: resourcemanager
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
        ports:
        - containerPort: 8088
